name: Build iOS Dev Client

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.4"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          npm install -g expo
          npm ci

      - name: Expo prebuild
        run: |
          npx expo prebuild --platform ios --clean

      - name: Patch Podfile
        run: |
          cd ios
          if ! grep -q "pod 'fmt'" Podfile; then
            ruby -e '
              txt = File.read("Podfile")
              txt.sub!(
                "post_install do |installer|",
                "pod '\''fmt'\'', '\''10.1.1'\''\n\npost_install do |installer|"
              )
              File.write("Podfile", txt)
            '
          fi

      - name: Install Pods
        run: |
          cd ios
          pod install

      - name: Read App Name
        run: |
          echo "APP_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV

      - name: Build Archive
        run: |
          xcodebuild \
          -workspace ios/${APP_NAME}.xcworkspace \
          -scheme ${APP_NAME} \
          -configuration Debug \
          -sdk iphoneos \
          -archivePath build/${APP_NAME}.xcarchive \
          archive \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGN_IDENTITY=""

      - name: Export IPA
        run: |
          mkdir Payload
          cp -R build/${APP_NAME}.xcarchive/Products/Applications/${APP_NAME}.app Payload/
          zip -r ${APP_NAME}.ipa Payload

      - uses: actions/upload-artifact@v4
        with:
          name: ipa
          path: ${{ env.APP_NAME }}.ipa
